languageCode = "ja-jp"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseURL = 'http://shingohry.github.io/'
canonifyurls = true
title = "shingohry"
author = "shingohry"
theme = "pixyll"
# disqusShortname = "sitename"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  # search_engine = true
  # google_analytics_id = "XX-XXXXXXXX-X"
  twitter_username = "shingohry"
  paginate = 5
